# Generated by Django 4.2.16 on 2024-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
