# Generated by Django 4.2.16 on 2024-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_db',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
